// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import WeekdayToggleController from "./weekday_toggle_controller"
application.register("weekday-toggle", WeekdayToggleController)

import UnitSelectController from "./unit_select_controller"
application.register("unit-select", UnitSelectController)

import CardPaginationController from "./card_pagination_controller"
application.register("card-pagination", CardPaginationController)

import QuizRunnerController from "./quiz_runner_controller"
application.register("quiz-runner", QuizRunnerController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import CharacterPickerController from "./character_picker_controller"
application.register("character-picker", CharacterPickerController)
